app = "api-emojy"
primary_region = "gru"

[build.args]
GO_VERSION = "1.22.5"

[env]
PORT = "8080"
DB_HOST= "193.203.175.193"
DB_PORT= "3306"
DB_USER= "u465114395_lucasgddr5"
DB_NAME= "u465114395_hug"
DB_PASSWORD= "@MD11nice"

[http_service]
auto_start_machines = true
auto_stop_machines = true
force_https = true
internal_port = 8_080
min_machines_running = 0
processes = [ "app" ]

[[vm]]
cpu_kind = "shared"
cpus = 1
memory = "1gb"
memory_mb = 1_024